name: facata

on: [push]

jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, latest]
        postgresql-version: [latest]

    container: python:${{ matrix.python-version }}

    services:
      postgresql:
        image: postgres:${{ matrix.postgresql-version }}
        env:
          POSTGRES_PASSWORD: pw
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: pw
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=4

      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: pw
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=4
        ports:
          - 3305:3306

    steps:
      - name: Set up MariaDB Connector
        run: |
          apt update
          apt install --yes --no-install-recommends libmariadb3 libmariadb-dev
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock .[mariadb,pg8000,psycopg2,mysql-connector]

      - name: Run pytest tests
        run: >-
          python -m pytest -x -v
          --mariadb-host=mariadb
          --postgresql-host=postgresql
          --mysql-host=mysql
          test 

  checks:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pw
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: pw
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3

      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: pw
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=4
        ports:
          - 3305:3306

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up MariaDB Connector
        run: |
          sudo apt update
          sudo apt install --yes --no-install-recommends libmariadb3 libmariadb-dev
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8-alphabetize black .[mariadb,pg8000,psycopg2,mysql-connector]

      - name: Run checks
        run: |
          black --check .
          python -m doctest -o ELLIPSIS README.adoc
          python setup.py check
          flake8 .
